#!/bin/sh

# Suppress kernel messages
dmesg -n 1

# Mount file systems
mkdir proc sys tmp
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp

# Networking
/etc/ethernet.sh

# Shell
/bin/sh
