#!/bin/sh

# Suppress kernel messages
dmesg -n 1

# Mount file systems
mkdir proc sys
mount -t proc none /proc
mount -t sysfs none /sys

# Setup Static IP
ifconfig eth0 10.0.2.15
route add default gw 10.0.2.2

# Shell
# /bin/sh: can't access tty; job control turned off
ln -s /dev/console /dev/tty
setsid cttyhack sh
/bin/sh
