#!/bin/sh

# Suppress kernel messages
dmesg -n 1

# Mount file systems
mkdir proc sys
mount -t proc none /proc      # ps
mount -t sysfs none /sys      # sys/class/net/eth0
mount -t devtmpfs none /dev   # dev/urandom (https)

# Setup Static IP
ifconfig eth0 10.0.2.15
route add default gw 10.0.2.2

# elinks
export TERM=xterm-256color

# Shell
# https://wiki.gentoo.org/wiki/Custom_Initramfs#Job_control
setsid cttyhack sh
