#!/bin/sh

# Suppress kernel messages
dmesg -n 1

# Mount file systems
mkdir proc sys
mount -t proc none /proc
mount -t sysfs none /sys

# Setup Static IP
# https://wiki.gentoo.org/wiki/Custom_Initramfs#Static_IP
ifconfig eth0 10.0.2.15
route add default gw 10.0.2.2

# Start shell
/bin/sh
